apiVersion: v1
kind: Service
metadata:
  name: aninaka-anime-api
  namespace: aninaka
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: aninaka-anime-api
  type: NodePort
